extends: "@cerner/terra"
rules:
  react/forbid-prop-types: off
globals:
  enzyme: readonly
  enzymeIntl: readonly
overrides:
  - files:
      - "packages/**/jest/**/*"
    rules:
      import/no-extraneous-dependencies: off
